apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/description: my wonderful app
  labels:
    application: myapp
    size: medium
    team: group:default/team-a
  name: myapp-prod